"""Normalise every source drawing into _includes/icons/glass-candidates/.

VIEWING COPIES FOR /dev/glasses/ SECTION 6, and nothing else. Not published
icons, not in `all_icons`, never referenced by a real page.

WHY A SECOND DIRECTORY IS NEEDED AT ALL. `_design_sources/cocktails/glasses/`
holds Helen's raw Inkscape exports, and Jekyll cannot reach them: `include`
reads only from `_includes/`, and there is no plugin here that loads an
arbitrary path. So the swatch page needs normalised copies somewhere
includable.

WHY NOT `_includes/icons/glasses/`. That directory IS the published set and
`tests/test_cocktails.py::test_all_icons_matches_the_icon_directory` asserts it
matches `all_icons` in both directions. Dropping 38 candidates in there fails
that test immediately, and rightly -- a reject sitting beside the shipped icons
is exactly the confusion the test exists to prevent. This sibling directory is
invisible to it, because that test globs non-recursively.

AND WHY THE LIST GOES TO `_data/`. Jekyll cannot enumerate a directory, so the
page has to be handed the names. `_data/dev_glass_candidates.yml` is written
here, in the same run, so regenerating the copies and updating the page is one
step rather than two that can drift.

Run from anywhere: `python3 scripts/build_glass_candidates.py`.
"""
import importlib.util
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "_design_sources" / "cocktails" / "glasses"
DST = ROOT / "_includes" / "icons" / "glass-candidates"
LISTING = ROOT / "_data" / "dev_glass_candidates.yml"

# Reuse the real normaliser, guards and all -- the transform-count check
# especially, since several candidates carry nested transforms. Importing it is
# safe: it has a __main__ guard (it did not always, and the day it did not, an
# import deleted all 26 published icons before the importer's first line ran).
_spec = importlib.util.spec_from_file_location(
    "normalise_glass_icons", ROOT / "scripts" / "normalise_glass_icons.py")
nrm = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(nrm)


def main():
    DST.mkdir(parents=True, exist_ok=True)
    for old in DST.glob("*.svg"):
        old.unlink()

    written, skipped = [], []

    for p in sorted(SRC.glob("*.svg")):
        stem = p.stem.replace("glass-", "")
        try:
            svg = nrm.normalise(p.read_text(encoding="utf-8"), stem, "glass-icon-line")
        except SystemExit as e:
            # A source that cannot be normalised is reported, never skipped
            # silently -- a candidate missing from the drawer looks like a
            # drawing that was never made.
            skipped.append((p.name, str(e)))
            continue
        (DST / f"{stem}.svg").write_text(svg, encoding="utf-8")
        written.append(stem)

    # THE SUPERSEDED DOUBLE, recovered from git rather than from the working
    # tree. When a drawing is replaced, the previous one is gone from
    # _design_sources the moment the new file is copied over it -- and the
    # whole point of the drawer is comparing the new against the old. Helen,
    # 2026-08-26: "It's possible I'll prefer the original one, the one I
    # thought I'd lost."
    #
    # Best-effort: on a fresh clone with no such history this simply does not
    # appear, which is correct, rather than failing the build of the page.
    try:
        prev = subprocess.run(
            ["git", "show",
             "HEAD:_design_sources/cocktails/glasses/glass-old-fashioned-double.svg"],
            capture_output=True, text=True, check=True, cwd=ROOT).stdout
        name = "old-fashioned-double-previous"
        (DST / f"{name}.svg").write_text(
            nrm.normalise(prev, name, "glass-icon-line"), encoding="utf-8")
        written.append(name)
    except (subprocess.CalledProcessError, SystemExit) as e:
        skipped.append(("old-fashioned-double-previous (from git)", str(e)))

    header = [
        "# GENERATED by scripts/build_glass_candidates.py -- do not hand-edit.",
        "#",
        "# The drawings in _design_sources/cocktails/glasses/, normalised into",
        "# _includes/icons/glass-candidates/ so /dev/glasses/ can show them.",
        "# Jekyll cannot list a directory, so the list lives here.",
        "#",
        "# VIEWING COPIES ONLY. Not published icons, not in glasses.yml",
        "# `all_icons`, and deliberately in a sibling directory the icon-set",
        "# tests cannot see. A name here with no counterpart in",
        "# _includes/icons/glasses/ is a drawing nothing uses -- a superseded",
        "# option or a reject, kept because the losers are the evidence for the",
        "# choice that was made.",
    ]
    LISTING.write_text(
        "\n".join(header + [f"- {n}" for n in sorted(written)]) + "\n",
        encoding="utf-8")

    print(f"{len(written)} candidates -> {DST.relative_to(ROOT)}")
    print(f"list -> {LISTING.relative_to(ROOT)}")
    for name, why in skipped:
        print(f"  SKIPPED {name}: {why[:100]}")


if __name__ == "__main__":
    main()
