"""Where each glass's BASE sits, so a label can be centred under it.

    python3 scripts/glass_base_centres.py --check    # diff, exit 1 if stale
    python3 scripts/glass_base_centres.py --write    # rewrite the block

A LABEL CENTRED ON A DRAWING'S BOX IS CENTRED ON ITS HANDLE TOO. Helen,
2026-09-29, on /cocktails/reference/glasses/: "The text isn't always centred
underneath the glass. For example, the text under the normal mug is way off to
the right, and the text for mule mug and pineapple are slightly right of
centre." Every label was centred exactly -- on the viewBox, which for a mug
includes the handle and for the pineapple its umbrella. The eye centres a
glass on what it STANDS on.

So this measures that: each published icon is rasterised with the repo's own
`svgrender`, the ink in its bottom band is found, and the centre of that band
is recorded as a signed fraction of the drawing's width from the centre of its
viewBox. Negative means the base is left of centre (the handle pulls the box
right). The glasses page shifts each drawing by minus that much, so its base
sits over the label.

GENERATED, because a number typed from a screenshot is right for the drawing
it was measured on and silently wrong after the next redraw.
tests/test_cocktails.py::test_glass_base_centres_are_current runs `check()`.

ONLY THE ONES THAT MATTER ARE WRITTEN. Under `THRESHOLD` of the width the
offset is the stroke's own asymmetry, not the drawing's, and a list of 27
near-zeros would hide the four that are real.
"""
import argparse
import difflib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import svgrender  # noqa: E402

ICONS = ROOT / "_includes" / "icons" / "glasses"
GLASSES = ROOT / "_data" / "cocktails" / "glasses.yml"
BEGIN = "# >>> GENERATED by scripts/glass_base_centres.py -- do not edit by hand"
END = "# <<< END GENERATED base_centre"
THRESHOLD = 0.01
HEIGHT_PX = 300
INK = 128


def base_centre(svg):
    """Signed offset of the base's centre from the viewBox centre, / width."""
    paths, viewbox, translate, _ = svgrender.parse_icon(svg)
    W, H, px = svgrender.render(paths, viewbox, height_px=HEIGHT_PX, translate=translate)
    rows = [y for y in range(H) if any(px[y * W + x] < INK for x in range(W))]
    bottom = max(rows)
    band = range(bottom - max(2, H // 25), bottom + 1)
    xs = [x for y in band for x in range(W) if px[y * W + x] < INK]
    return ((min(xs) + max(xs)) / 2 - W / 2) / W


def render_block():
    lines = [BEGIN, "base_centre:"]
    for svg in sorted(ICONS.glob("*.svg")):
        off = base_centre(svg)
        if abs(off) >= THRESHOLD:
            lines.append(f"  {svg.stem}: {off:.3f}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def regenerated():
    old = GLASSES.read_text(encoding="utf-8")
    start, end = old.find(BEGIN), old.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"{GLASSES.relative_to(ROOT)}: marker pair not found:\n"
                         f"  {BEGIN}\n  {END}")
    return old, old[:start] + render_block() + old[end + len(END) + 1:]


def check():
    """(a unified diff of what --write would do, problems) -- the test runs this."""
    old, new = regenerated()
    return "".join(difflib.unified_diff(
        old.splitlines(True), new.splitlines(True),
        "glasses.yml", "glasses.yml (regenerated)")), []


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    if args.write:
        GLASSES.write_text(regenerated()[1], encoding="utf-8")
        return 0
    diff, _ = check()
    if diff:
        sys.stdout.write(diff)
        print("\nStale. Run: python3 scripts/glass_base_centres.py --write")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
