"""Typical capacity and height per glass type, from the sourced survey (#1238).

    python3 scripts/glass_survey_stats.py --check    # diff, exit 1 if stale
    python3 scripts/glass_survey_stats.py --write    # rewrite the block

THE SURVEY IS THE FACT AND THE STATISTICS ARE ITS SHADOW. Every product in
`_data/cocktails/glass_survey.yml` carries its own figure and the page it came
from; `_data/cocktails/glasses.yml` carries only what those figures add up to --
n, min, median, mean and max -- between a pair of marker comments. Typing the
summary by hand would be a second copy of the survey waiting to disagree with
it, so it is generated, and
tests/test_cocktails.py::test_glass_survey_statistics_are_current runs `--check`
so the two cannot drift.

WHAT COUNTS TOWARDS A CAPACITY. `brimful`, `unstated` and `documented` do; a
`nominal` figure does NOT, because it is a pour size or a filling line rather
than what the glass holds -- one wine glass in the survey is sold as "125 ml",
its design pour, and averaging that in as a capacity would call it a thimble.
The entry stays in the survey (it is a true fact about the page) and simply is
not counted. Heights have no such distinction: an overall height is an overall
height.

`exclude: "<why>"` TAKES A WHOLE ROW OUT OF BOTH, and it is the one place a
row is judged rather than read. The rule for getting INTO the survey is that
the maker or retailer names the product as that type, which is objective and
admits a few things that are plainly not it -- a flat stemless tumbler sold as
an "absinthe glass", a novelty beer-mug shot. They stay recorded, with the
reason, so the judgement is visible and reversible.

A SPEC, NOT AN INVENTORY. Helen, 2026-09-28: "I don't want inventory, just
spec. I might buy new glasses... let's offer rules, then I'll happily break
them in the kitchen." These are what the glass types on the market measure,
not what is in the cupboard.
"""
import argparse
import difflib
import pathlib
import statistics
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SURVEY = ROOT / "_data" / "cocktails" / "glass_survey.yml"
GLASSES = ROOT / "_data" / "cocktails" / "glasses.yml"

BEGIN = "# >>> GENERATED by scripts/glass_survey_stats.py from glass_survey.yml -- do not edit by hand"
END = "# <<< END GENERATED"

# The capacity bases a figure may have, and the ones that count towards a
# capacity. See the docstring for why `nominal` is recorded and not counted.
BASES = {"brimful", "unstated", "nominal", "documented"}
COUNTED = {"brimful", "unstated", "documented"}


def summary(values):
    """n, min, median, mean, max -- whole numbers, because the inputs are."""
    return {
        "n": len(values),
        "min": round(min(values)),
        "median": round(statistics.median(values)),
        "mean": round(statistics.mean(values)),
        "max": round(max(values)),
    }


def load_survey():
    return yaml.safe_load(SURVEY.read_text(encoding="utf-8"))["survey"]


def statistics_by_type(survey):
    """{key: {"ml": summary | None, "height_mm": summary | None}}, in key order."""
    ml, height = {}, {}
    for row in survey:
        key = row["glass"]
        ml.setdefault(key, [])
        height.setdefault(key, [])
        if row.get("exclude"):
            continue
        if row.get("capacity_basis") in COUNTED and row.get("capacity_ml") is not None:
            ml[key].append(row["capacity_ml"])
        if row.get("height_mm") is not None:
            height[key].append(row["height_mm"])
    return {
        key: {
            "ml": summary(ml[key]) if ml[key] else None,
            "height_mm": summary(height[key]) if height[key] else None,
        }
        for key in sorted(ml)
    }


def render(stats):
    width = max(len(k) for k in stats) + 1

    def line(key, s):
        value = "null" if s is None else (
            f"{{n: {s['n']}, min: {s['min']}, median: {s['median']}, "
            f"mean: {s['mean']}, max: {s['max']}}}")
        return f"  {key + ':':<{width}} {value}"

    out = [BEGIN, "typical_ml:"]
    out += [line(k, v["ml"]) for k, v in stats.items()]
    out.append("typical_height_mm:")
    out += [line(k, v["height_mm"]) for k, v in stats.items()]
    out.append(END)
    return "\n".join(out) + "\n"


def problems_with(survey, glasses):
    """Every survey key must be a glass the site declares, and every icon covered."""
    icons = set(glasses["all_icons"])
    extra = set((glasses.get("survey_only_types") or {}).keys())
    problems = []
    for i, row in enumerate(survey):
        where = f"survey row {i} ({row.get('product')!r})"
        if row.get("glass") not in icons | extra:
            problems.append(f"{where}: glass {row.get('glass')!r} is neither an icon "
                            "in all_icons nor declared in survey_only_types")
        if row.get("capacity_basis") not in BASES:
            problems.append(f"{where}: capacity_basis {row.get('capacity_basis')!r} "
                            f"is not one of {sorted(BASES)}")
        if not str(row.get("source", "")).startswith(("http://", "https://")) \
                and not row.get("citation"):
            problems.append(f"{where}: no source URL and no citation")
    covered = {row["glass"] for row in survey}
    for icon in sorted(icons - covered):
        problems.append(f"icon {icon!r} has no survey rows at all")
    return problems


def regenerate(text, block):
    start, end = text.find(BEGIN), text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"{GLASSES.relative_to(ROOT)}: marker pair not found:\n"
                         f"  {BEGIN}\n  {END}")
    return text[:start] + block + text[end + len(END) + 1:]


def regenerated():
    """(current glasses.yml text, what --write would make it, problems)."""
    survey = load_survey()
    old = GLASSES.read_text(encoding="utf-8")
    problems = problems_with(survey, yaml.safe_load(old))
    if problems:
        return old, old, problems
    return old, regenerate(old, render(statistics_by_type(survey))), []


def check():
    """(a unified diff of what --write would do, problems).

    tests/test_cocktails.py runs exactly this, so `--check` and the suite
    cannot disagree about what stale means.
    """
    old, new, problems = regenerated()
    diff = "".join(difflib.unified_diff(
        old.splitlines(True), new.splitlines(True),
        "glasses.yml", "glasses.yml (regenerated)"))
    return diff, problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="diff, exit 1 if stale")
    mode.add_argument("--write", action="store_true", help="rewrite the block")
    args = parser.parse_args(argv)

    if args.write:
        _, new, problems = regenerated()
        if problems:
            print("\n".join(problems))
            return 1
        GLASSES.write_text(new, encoding="utf-8")
        return 0
    diff, problems = check()
    if problems or diff:
        print("\n".join(problems))
        sys.stdout.write(diff)
        print("\nStale. Run: python3 scripts/glass_survey_stats.py --write")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
